[profile.default]
src = 'src'
test = 'tests'
script = 'scripts'
out = 'out'
libs = ['lib']
remappings = [
  'aave-helpers/=lib/aave-helpers/src/',
  'solidity-utils/=lib/solidity-utils/src/'
]
fs_permissions = [{ access = "write", path = "./reports" }]

solc='0.8.19'

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
optimism = "${RPC_OPTIMISM}"
avalanche = "${RPC_AVALANCHE}"
polygon = "${RPC_POLYGON}"
arbitrum = "${RPC_ARBITRUM}"
fantom = "${RPC_FANTOM}"
metis = "${RPC_METIS}"
base = "${RPC_BASE}"

[etherscan]
ethereum={key="${ETHERSCAN_API_KEY_MAINNET}", chain=1 }
optimism={key="${ETHERSCAN_API_KEY_OPTIMISM}",chain=10}
avalanche={key="${ETHERSCAN_API_KEY_AVALANCHE}",chain=43114}
polygon={key="${ETHERSCAN_API_KEY_POLYGON}",chain=137}
arbitrum={key="${ETHERSCAN_API_KEY_ARBITRUM}",chain=42161}
metis={ key="any", chain=1088, url='https://andromeda-explorer.metis.io/' }
base={key="${ETHERSCAN_API_KEY_BASE}",chainId=8453}

# See more config options https://github.com/gakonst/foundry/tree/master/config
