export const V3_EXECUTOR_ABI = [
  {
    anonymous: false,
    inputs: [
      {indexed: true, internalType: 'address', name: 'target', type: 'address'},
      {indexed: false, internalType: 'uint256', name: 'value', type: 'uint256'},
      {indexed: false, internalType: 'string', name: 'signature', type: 'string'},
      {indexed: false, internalType: 'bytes', name: 'data', type: 'bytes'},
      {indexed: false, internalType: 'uint256', name: 'executionTime', type: 'uint256'},
      {indexed: false, internalType: 'bool', name: 'withDelegatecall', type: 'bool'},
      {indexed: false, internalType: 'bytes', name: 'resultData', type: 'bytes'},
    ],
    name: 'ExecutedAction',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {indexed: true, internalType: 'address', name: 'previousOwner', type: 'address'},
      {indexed: true, internalType: 'address', name: 'newOwner', type: 'address'},
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    inputs: [
      {internalType: 'address', name: 'target', type: 'address'},
      {internalType: 'uint256', name: 'value', type: 'uint256'},
      {internalType: 'string', name: 'signature', type: 'string'},
      {internalType: 'bytes', name: 'data', type: 'bytes'},
      {internalType: 'bool', name: 'withDelegatecall', type: 'bool'},
    ],
    name: 'executeTransaction',
    outputs: [{internalType: 'bytes', name: '', type: 'bytes'}],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{internalType: 'address', name: '', type: 'address'}],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{internalType: 'address', name: 'newOwner', type: 'address'}],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {stateMutability: 'payable', type: 'receive'},
];
